theme: jekyll-theme-minimal
title: Traffic Accidents in Relation to Major Professional Sporting Events - An Analysis of Four Southeastern Cities 
logo: /gdc-world-happiness-report-2019.jpg
description: By Holden Herrell, Karima Hunter, and Vaibhav Mehta
