theme: jekyll-theme-minimal
title: Traffic Accidents in Relation to Major Professional Sporting Events - An Analysis of Four Southeastern Cities 
logo: /traffic.jpg
description: By Holden Herrell, Karima Hunter, and Vaibhav Mehta
